### VALUES YOU SHOULD CHANGE ###

# GENERAL SITE SETTINGS
# title: This will be displayed as the website's name in your browser tab.
title: Duc Anh Nguyen
# description: This will be meta HTML tag content. This can be ignored.
description: Personal website powered by Jekyll
# baseurl: The subpath of your site
# > set this to "", if you renamed the repository to <user>.github.io
baseurl: ""

# LANDING PAGE
# username: This will displayed on the landing page as your name.
username: Duc Anh Nguyen
# typing_text: This will be typed before 'scroll down for more'.
# > set this to your job title, e.g. Fullstack Developer
typing_text: M. Sc. Business Analytics & Econometrics
# email: Your E-Mail address for the email button.
email: duc.anh.nguyen@outlook.de
# For every social button you want to display, set your username or userid
# If you do not use one of the following websites, then leave it empty
# > twitter_username:
github_username: ducanhnguyen99
codepen_username: 
dev_username: 
linkedin_username: duc-anh-nguyen-09132b21a
twitter_username: 

# emojis used: https://emoji-css.afeld.me/, with stylesheet under section-aboutme.html
# ABOUT ME SECTION
# show_aboutme_card:
# > setting this to true, will display the About Me section
# > setting this to false, will omit the About Me section
show_aboutme_card: true
# about_me_title: The will be displayed as the title in the About Me section
about_me_title: Who am I
# about_me_description: This will be displayed under the title.
about_me_description: > 
  <i class="em em-wave emoji-spacing" aria-role="presentation" aria-label="WAVING HAND SIGN"></i>  
  Hi, I'm Duc Anh Nguyen from Germany with Vietnamese roots. <br><br> 

  <i class="em em-blue_book emoji-spacing" aria-role="presentation" aria-label="BLUE BOOK"></i>  
  I'm finshing my M.Sc. Business Analytics & Econometrics degree at the University of Cologne. <br><br>

  <i class="em em-computer emoji-spacing" aria-role="presentation" aria-label="PERSONAL COMPUTER"></i>  
  My data-centric work experience spans AI, predictive analytics, and software development. <br><br> 

  <i class="em em-bulb emoji-spacing" aria-role="presentation" aria-label="ELECTRIC LIGHT BULB"></i>  
  I'm passionate about using data to drive innovation and like to evaluate ideas with my peers. <br><br> 

  <i class="em em-rocket emoji-spacing" aria-role="presentation" aria-label="ROCKET"></i>  
  I'm eager to learn, grow and make a sustainable impact on people's lives. <br><br> 

  <i class="em em-volleyball emoji-spacing" aria-role="presentation" aria-label="VOLLEYBALL"></i>  
  In my free time I enjoy volleyball, going to Catan tournaments and supporting my family’s sushi restaurant.

# SKILLS SECTION
# show_skills_card:
# > setting this to true, will display the Skills section
# > setting this to false, will omit the Skills section
show_skills_card: true
# about_me_title: The will be displayed as the title in the Skills section
skills_title: Skills

# TIMELINE SECTION
# show_timeline_card:
# > setting this to true, will display the Timeline section
# > setting this to false, will omit the Timeline section
show_timeline_card: true
# timeline_title: The will be displayed as the title in the Timeline section
timeline_title: Education & Experience
# cv_download_link: The link where you host your cv.
# > e.g. you share your cv on your dropbox, then add the dropbox link here
cv_download_link: https://drive.google.com/file/d/14fj4d_OF06uljguL_wGAObCf_sU-F0Ko/view?usp=sharing

# PROJECTS SECTION
# show_projects_card:
# > setting this to true, will display the Projects section
# > setting this to false, will omit the Projects section
show_projects_card: true
# show_projects:
# > setting this to true, will display your listed projects in _data/projects.yml
# > setting this to false, will omit your listed projects
show_projects: true
# projects_title: The will be displayed as the title of your projects
projects_title: Personal Project Ideas
# show_os_projects:
# > setting this to true, will display your public projects on github
# > setting this to false, will omit your public projects on github
show_os_projects: true
# os_projects_title: The will be displayed as the title of your open source projects
os_projects_title: GitHub Projects

# CONTACT SECTION
# show_contact_card:
# > setting this to true, will display the Contact section
# > setting this to false, will omit the Contact section
show_contact_card: true
# contact_title: The will be displayed as the title in the Contact section
contact_title: Get In Touch
# contact_description: This will be displayed under the title.
contact_description: >
  Currently, I am seeking new opportunities after my studies, particularly traineeships and full-time roles. 
  My passion lies in data analytics and science, with a focus on sectors such as the energy market, healthcare, mobility, 
  and other fields that impact climate and people's lives. If you have opportunities or ideas that align with these 
  interests — or simply want to connect — please reach out. I welcome discussions about how I can contribute to impactful projects.

# GITHUB-METADATA
# Set this to your forked repository
# > e.g. <user>/<user>.github.io
repository: ducanhnguyen99/ducanhnguyen99.github.io
projects:
  # sortby:
  # > set this to pushed, if you want to sort your github repositories by time.
  # > set this to stars, if you want to sort your github repositories by stars.
  sort_by: pushed
  exclude:
    # archived:
    # > setting this to true, will exclude archived repositories
    # > setting this to false, will also display archived repositories
    archived: false
    # forks:
    # > setting this to true, will exclude forked repositories
    # > setting this to false, will also display forked repositories
    forks: false
    # projects: A list of the repository names you want to exclude from the listing.
    projects:
    # - repo1-to-be-excluded
    # - repo2-to-be-excluded

# GOOGLE-ANALYTICS
# Set the id, if you want to track your website with Google Analytics
# > set this to "", if you do not want to track with Google Analytics
google-analytics:
  id: "UA-158757509-2"

### END OF VALUES YOU SHOULD CHANGE ###

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
    "vendor"
  ]
